language: objective-c  
osx_image: xcode9.1
xcode_workspace: TeslaSwift.xcworkspace
xcode_scheme: TeslaSwift
xcode_sdk: iphonesimulator11.1
notifications:
  email: false
before_install:
 - rvm install ruby-2.2.2
 - gem install cocoapods --pre
 - pod repo update --silent
script: 
 - xcodebuild -workspace 'TeslaSwift.xcworkspace' -scheme 'TeslaSwift' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test
